version: '2'
services:
  dress_mysql:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
      MYSQL_PASSWORD: "root"
    networks:
      - dress_network
  web_app:
    build:
      context: .
      dockerfile: ./dockerfile
    image: app/dress:v1
    ports:
      - "81:80"
    depends_on:
      - dress_mysql
    networks:
      - dress_network

networks:
  dress_network:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
